name: stream_feed
description: Stream Feed official Dart SDK. Build your own feed experience using
  Dart and Flutter.
version: 0.6.0+3
repository: https://github.com/GetStream/stream-feed-flutter
issue_tracker: https://github.com/GetStream/stream-feed-flutter/issues
homepage: https://getstream.io/
environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  collection: ^1.17.0
  dio: ^5.3.3
  equatable: ^2.0.5
  faye_dart:
    git:
      url: https://github.com/gadzhov/stream-feed-flutter.git
      ref: master
      path: packages/faye_dart
  http_parser: ^4.0.2
  intl: ^0.18.0
  jose: ^0.3.4
  json_annotation: ^4.8.1
  logging: ^1.2.0
  meta: ^1.9.1
  mime: ^1.0.4

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  mocktail: ^1.0.1
  test: ^1.24.9
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
